### ISSUE TITLE
Possible bypass with "http://localhoste\ @localhost "

### ISSUE THREAD

**Issue by felippe-regazio** [felippe-regazio/ssrfcheck#2]
The library is validating as Safe the invalid string: `http://localhoste\@localhost`.

<img width="491" alt="image" src="https://github.com/felippe-regazio/ssrfcheck/assets/31618881/b453a624-33f0-4a58-81d7-91a0179bf0f7">

<img width="751" alt="image" src="https://github.com/felippe-regazio/ssrfcheck/assets/31618881/01bb2753-3e8d-4899-b007-43c8cbaf860d">

**Comment by felippe-regazio** [comment]
Solved

**Comment by 0xTeles** [comment]
The bypass still possible
<img width="770" alt="image" src="https://github.com/felippe-regazio/ssrfcheck/assets/23142366/405347b7-c108-45ac-a7d2-3cea8a090677">

**Comment by felippe-regazio** [comment]
Solved in v1.0.5
